#+AUTHOR:Jonatan Ahumada
#+TITLE: Modelo de literariedad basado en la lingüistica de Roman Jakobson
#+STARTUP: beamer
#+OPTIONS:   H:2
#+BEAMER_THEME: Rochester [height=20pt]
#+LATEX_HEADER: \logo{\includegraphics[height=0.5cm]{./assets/lOGO-HORIZONTAL-KONRAD-COLOR.jpg}}
#+LATEX_HEADER: \usepackage[spanish]{babel}

#+SUBTITLE: Fundación Universitaria Konrad Lorenz
#+LANGUAGE: es


* Contexto

** ¿Qué es /literariedad/?  

   Es una presunta /característica/ que distingue un texto literario de
   otro no literario.

   Por ejemplo:

  - Manual de un carro vs. un poema de Jose Asunción Silva (fácil)
  - Artículo periodístico  vs. cuento corto  (normal)
  - /50 sombras de Gray/ vs. /Ulysses/ (difícil)

    



** Antecedentes: Roman Jakobson

*** ¿Quién fue?
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:
    Roman Jakobson fue un lingüista ruso americano. Se considera una
    figura clave tanto en movimiento del /formalismo ruso/, así como
    en el /estructuralista/.  La lingüística de Jakobson se basa en
    los postulados de la lingüistica de Saussure, *pero* propuso una
    crítica a las ideas de Saussure.


*** Cita
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :BEAMER_ENV: block
    :END:
    #+begin_quote
    The fundamental role which these two operations play in language
    was clearly realized by Ferdinand de Saussure. Yet of the two
    varieties of combination-concurrence and concatenation-it was only
    the latter, the temporal sequence, which was recognized by the
    Geneva linguist. 
    \cite[p. 99]{jakobson1956two}
    #+end_quote




**  Metáfora y metonimia
*** Libro
   :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:
\begin{figure}
    \includegraphics[width=0.6\textwidth]{./assets/ejemplo_metafora.png}
\caption{Ejemplo de metáfora}
 \end{figure}

 \begin{figure}
    \includegraphics[width=\textwidth]{./assets/ejemplo_metonimia.png}
\caption{Ejemplo de metonimia}
 \end{figure}
 

*** Citas
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:
    
   \tiny

      \begin{block}{Selección/Metáfora}
A selection between alternatives implies the possibility
of substituting one for the other, equivalent in one respect and differ­
ent in another. Actually, selection and substitution are two faces of the
same operation. \cite[p.98]{jakobson1956two}


   \end{block}
   
   \begin{block}{Combinación/Metonimia}
Any linguistic sign involves two modes of arrangement: Any sign is made up of constituent signs and/or
occurs only in combination with other signs. This means that any lin­
guistic unit at one and the same time serves as a context for simpler
units and/or finds its own context in a more complex linguistic unit.
\cite[p.99]{jakobson1956two}
   \end{block}



   \normalsize

** Ejemplos pictóricos de metáfora y metonimia

*** Metáfora
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:

    \begin{figure}
   \caption{\emph{Cisnes reflejando elefantes} de Salvador Dalí}
 \includegraphics[width=\textwidth]{./assets/arte_dali.jpg}
   
    \end{figure}

*** Metonimia
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:

\begin{figure}
    \includegraphics[width=\textwidth]{./assets/arte_green.png}
\caption{\emph{9 grados} de Denise Green}
 \end{figure}
 
** La pregunta
   

   
   \begin{block}{}
      ¿Cómo medir
      computarizadamente la \emph{literariedad} de un texto según el marco de la
      lingüística de Jakobson?
   \end{block}




* Objetivos
** General
   \begin{block}{General}

Diseñar e implementar un modelo que, dado un corpus de texto, produzca
   indicadores para el concepto de \emph{literariedad} que plantea Roman Jakobson.
     \end{block}
     
** Específicos
1) Construir el corpus necesario para representar el /eje sincrónico/.
2) Diseñar e implementar el algoritmo para calcular la /metáfora/ sobre un corpus.
3) Diseñar e implementar algoritmo para calcular la /metonimia/ sobre un corpus.
4) Seleccionar y unir los textos que serán procesados (corpus objetivo) por el algoritmo.
3) Correr el algoritmo sobre los corpus objetivo.
4) Evaluar el algoritmo de manera cuantitativa y cualitativa.

** Alcance

1) Modelos de prototipo

2) Corpus de acceso libre (Corpus de Brown)

3) Herramientas 'básicas' de NLP en Python


* Diseño Metodológico
  
** CRISP-DM

   \begin{figure}
   \caption{Pasos de CRISP-DM}
    \includegraphics[width=0.8\textwidth]{./assets/metodologia.png}
    
    \end{figure}

* Entendimiento del negocio
** Entendimiento del negocio
   
Cada algoritmo recibe un mensaje  $m$ de entrada con:
\begin{block}{Entrada}
\begin{itemize}
\item cadena de cualquier longitud
\item sin POS
\item sin set de entrenamiento
\end{itemize}
\end{block}
 produce:

\begin{block}{Salida}
\begin{itemize}
\item  Un valor continuo para dicho mensaje 
\item  Entre más alto el valor, más fuerte es esa característica (metáfora y/o metonímia)
\end{itemize}
\end{block}

* Entendimiento de los datos
** Entendimiento de los datos                                             :A: 
  

*** texto
   :PROPERTIES:
   :BEAMER_COL: 0.48
   :END:
   
   \begin{block}{Corpus de referencia}
   Modela el estado actual de la \emph{lengua}.
   Eje de sicnronía en Saussure.
   \end{block}

   \begin{block}{Red semántica}
    Modela el \emph{lenguaje}: la capacidad de asociar ideas con símbolos.
   \end{block}

   \begin{block}{Corpus objetivo}
    Modela el \emph{habla}. El mensaje que será sometido a análisis.
   \end{block}
  
   

*** graficos
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:
    \begin{figure}
    \includegraphics[width=\textwidth]{./assets/sistema-comunicacion.png}
    \caption{El circuito linguístico. Tomado de \cite{alonso1945curso}}
    \end{figure}

    \begin{figure}
 
    \includegraphics[width=\textwidth]{./assets/sistema-comunicacion2.png}
 \caption{El circuito linguístico (visión alterna). Tomado de \cite{alonso1945curso}}
    \end{figure}

** Criterios                                                              :C:

*** Corpus de Brown
    :PROPERTIES:
    :BEAMER_col: 0.48
    :END:
    \begin{block}{Corpus de Brown}
     \small
     \begin{itemize}
     \item todos los documentos son del año 1961,
     \item publicadas en Estados Unidos,
     \item hablantes nativos de inglés,
     \item comité de expertos,
     \item  muestra representativa del inglés,
     \item lista amplia de categorías,
     \item resultados  replicables,
     \item  documentos por categoría son proporcionales a los publicados
     \end{itemize}
     \end{block}
     \normalsize

*** Wordnet                                                               :D:
   :PROPERTIES:
   :BEAMER_col: 0.48
   :END:


    \begin{block}{Wordnet}
    Es una base de datos de \emph{relaciones conceptuales} entre palabras.
    \end{block}

    

     
    \begin{figure}
    \includegraphics[width=0.7\textwidth]{./assets/wordnet-relaciones.png}
    \caption{Ejemplo de relaciones entre conceptos en Wordnet. Tomado de \cite[p.30]{fellbaum_1998}}
    \end{figure}
** Resumen                                                                :B:


 
    \begin{figure}
    \includegraphics[height=\textheight]{./assets/entendimiento_de_los_datos.png}

    \end{figure}

* Preparación de los datos
** Preparación de los datos
 
 \begin{figure}
 \includegraphics[width=\textwidth]{./assets/preparacion_visualizacion.png}
 \end{figure}

    
       \begin{table}[!ht]
      \centering

      \begin{tabular}{|c|c|}
      \hline
        Atributo & Cantidad \\ \hline
        Textos en corpus de referencia & 60 \\ \hline
        Categorías en corpus de referencia  & 13 \\ \hline
       Textos en corpus objetivo & 70 \\ \hline
       Textos en muestra de corpus objetivo & 14 \\ \hline
       Muestras de corpus objetivo & 5 \\ \hline
       Categorías por muestra & 14  \\ \hline
       Total de textos usados & 130  \\ \hline
      \end{tabular}
  \caption{Resumen de datos utilizados}
  \label{tab:resumen_preparacion}
  \end{table}

* Modelamiento
** Modelamiento                                                           :A: 
  
*** Metáfora                                                          :texto:
    :PROPERTIES:
    :BEAMER_col: 0.48
    :END:

    \tiny
    \begin{block}{Metáfora}
\begin{equation}
\label{eq:mensaje}
mensaje = \{ w_1, w_2, w_3, \dots , w_j \}
\end{equation}

\begin{equation}
\label{eq:vector_semantico}
vector\ semantico(w) = \{s_1, s_2, s_3, \dots, s_j \} 
\end{equation}

\begin{equation}
\label{eq:vector_uso}
vector\ uso(w) = \{freq_{ref}(s_1),freq_{ref}(s_2),freq_{ref}(s_3), \dots, freq_{ref}(s_j) \} 
\end{equation}

\begin{equation}
\label{eq:promedio}
\mu = \frac{\Sigma_i^jfreq_{referencia}(s_i)}{j}
\end{equation}


\begin{equation}
\label{eq:uso}
uso(w) = \frac{freq_{objetivo}(w)}{\mu}
\end{equation}


\begin{equation}
\label{eq:indice_metafórico}
indice\ metaforico(mensaje) =  \Sigma_i^j uso(w_i)
\end{equation}

\end{block}
\normalsize
*** Ejemplo                                                         :ejemplo:
     :PROPERTIES:
     :BEAMER_col: 0.48
     :END:
     
         \begin{figure}
    \includegraphics[width=\textwidth]{./assets/codigo_vector_semantico.png}
    \caption{Ejemplo de implementación}
    \end{figure}

    \begin{figure}
 
    \includegraphics[width=\textwidth]{./assets/codigo_vector_uso.png}
 \caption{Ejemplo de implementación}
    \end{figure}


** Modelamiento                                                           :B:


*** Texto                                                             :texto:
        :PROPERTIES:
    :BEAMER_col: 0.48
    :END:
\tiny
\begin{block}{Metonimia}
\begin{equation}
\label{eq:ngramas}
N = \{n_1, n_2, n_3, \dots , n_j\}
\end{equation}

\begin{equation}
\label{eq:metonimia}
met(n_i) = \frac{letras\ iguales}{ set(letras(n_i1) + letras(n_i2))}
\end{equation}

\begin{equation}\label{eq:indice_metonimia}
indice\ metonimia = \Sigma_i^j met(n_i)
\end{equation}
\end{block}
\normalsize
***  Ejemplo                                                        :ejemplo:
    :PROPERTIES:
    :BEAMER_col: 0.48
    :END:

    \begin{figure}
    \includegraphics[width=\textwidth]{./assets/codigo_metonimia.png}
    \caption{Ejemplo de implementación}
    \end{figure}

    \begin{figure}
 
    \includegraphics[width=\textwidth]{./assets/metonimia.jpg}
    \caption{Concepto de metonimia}
    \end{figure}

** Diseño experimental                                                    :C:

*** Criterios cualitativos
   - H_1: Se espera que las categorías de ficción tengan un índice metafórico significativamente mayor que los de no-ficción.
   - H_2: Se espera que las categorias 'Reportage' y 'Editorial' tengan índices metafóricos similares a través de las muestras.
   - H_3: Se espera que la categoría 'Belles Lettres' tenga un indíce metafórico más alta entre las categorías de no-ficción.
   - H_4: Se espera que la categoria 'Learned' tenga un indice metonímico bajo en general.
*** Criterios cuantitativos
     Prueba ANOVA: ¿Los resultados que se obtuvieron son aleatorios?
* Despliegue
** Resultados por categorías


*** Metafora
     :PROPERTIES:
     :BEAMER_col: 0.48
     :END:
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{./resultados/graphs/total/accum_cat_metafora.png}

\caption{Metáfora través de las muestras }
\end{figure}

*** Metonimia
     :PROPERTIES:
     :BEAMER_col: 0.48
     :END:
     
\begin{figure}[H]
\includegraphics[width=\linewidth]{./resultados/graphs/total/accum_cat_metonimia.png}
\caption{Metonimia través de las muestras }
\centering

\end{figure}

** Resultados por metacategorías
 
*** Metafora
     :PROPERTIES:
     :BEAMER_col: 0.48
     :END:
     
\begin{figure}[H]
\centering
\includegraphics[width=0.9\linewidth]{./resultados/graphs/total/metafora_total.png}
\caption{\label{fig:metafora_total} Índice metafórico por metacategorías a través de muestras }
\end{figure}


*** Metonimia
     :PROPERTIES:
     :BEAMER_col: 0.48
     :END:
     
\begin{figure}[H]
\centering
\includegraphics[width=0.9\linewidth]{./resultados/graphs/total/metonimia_total.png}
\caption{\label{fig:metonimia_total} Índice metonímico por metacategoria a través de muestras }
\end{figure}

* Evaluación
** Evaluación y conclusiones
   \tiny
*** Evaluación
     :PROPERTIES:
    :BEAMER_col: 0.48
    :END:
  \begin{block}{Criterios cualitativos}
  \begin{table}[H]
  

      \begin{tabular}{|l|l|l}
      \hline
	 Criterio     &  Evaluación \\ \hline
         H_{1}  & Cumplió  \\
         H_{2}  & Cumplió\\
        H_{3}  & No cumplió \\
        H_{4}  & Cumplió\\
\hline
      \end{tabular}

  \end{table}
  \end{block}


 \begin{block}{Criterios cuantitativos}
  \begin{table}[H]
   

      \begin{tabular}{|l|l|l|}
      \hline
	 Indicador     &  F & p-value \\ \hline
         Metafora  & 51.41 & 9.81^{-10}  \\
         Metonimia  & 4.32 & 0.04 \\
         \hline

      \end{tabular}

  \end{table}
 \end{block}
 \normalsize

*** Conclusiones 
    :PROPERTIES:
    :BEAMER_col:  0.48
    :END:
    El modelo propuesto:
  
   1) produce valores cuantitativos capaces de 'distinguir'
      significativamente entre dos metacategorias: los textos de
      ficción y los de no-ficción,

2) parece avalar las observaciones de Jakobson en torno a la relación
   de la metonimia con el polo 'Realista' (periódicos, reportes,
   artículos, etc) y la metáfora con el polo del 'Romanticismo'
   (historias, fábulas, fantasía, etc),

3) tiene algunas ventajas y desventajas con respecto a un enfoque de
   Machine Learning. Como ventaja, no se requiere un /training
   set/. Como desventaja, el valor de los índices debe ser comparado
   entre textos según un contexto dado por el corpus de referencia.

** Trabajo futuro

    
*** Mejoramiento del algoritmo
     
-  Utilizar Tf-idf para matizar mejor el índice metafórico.
-  Hacer el índice metafórico sensible a los casos donde una palbra se use por debajo del promedio de uso.
-  Hacer el cálculo de similitud del índice metonímico con sílabas o fonemas.
-  Ofrecer la capacidad de personalizar la red semántica.

*** Mejoramiento de evaluación
- Aumentar el número de muestras hasta agotar el Corpus de Brown.
- Repetir el mismo diseño experimental en el Corpus de LOB, que tiene las mismas categorías que el de Brown.
- Utilizar los valores de los índices dentro como una característica en un escenario de Machine Learning. 

** Reflexión final

    \begin{figure}
    \includegraphics[width=0.8\textwidth]{./assets/literariedad_scatter.png}
    \caption{Metáfora y metonimia en cada documento}
    \end{figure}

** Bibliografía
\bibliographystyle{ieeetr}
\bibliography{biblio}
   
