#+AUTHOR:Jonatan Ahumada
#+TITLE: Modelo de literariedad basado en la lingüistica de Roman Jakobson
#+STARTUP: beamer
#+OPTIONS:   H:2
#+BEAMER_THEME: Rochester [height=20pt]
#+LATEX_HEADER: \logo{\includegraphics[height=0.5cm]{./assets/lOGO-HORIZONTAL-KONRAD-COLOR.jpg}}
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+SUBTITLE: Fundación Universitaria Konrad Lorenz
#+LANGUAGE: es


* Introducción

** ¿Qué es /literariedad/?  

   Es una presunta /característica/ que distingue un texto literario de
   otro no literario.

   Por ejemplo:

  - Manual de un carro vs. un poema de Jose Asunción Silva (fácil)
  - Artículo periodístico  vs. cuento corto  (normal)
  - /50 sombras de Gray/ vs. /Ulysses/ (difícil)


** Antecedentes: Los clásicos

   En los estudios clásicos, se encuentran teorías acerca de qué constituye
   un texto 'poético' o una buena 'narración'.

   - Fedro, Platón
   - Póetica, Aristóteles
   - Carta a los pisones, Horacio

   Sin embargo, el enfoque que toman estos autores no es *metódico* o *sistemático*
  
** Antecedentes: la linguística estructural

   En el siglo 20, Ferdinand de Saussure fundó la linguística general
   (también llamada estructural). Se considera al fenómeno del
   lenguaje como una estructura compuesta de varios componentes
   interdependientes, pero identificables.


** Antecedentes: Roman Jakobson

*** ¿Quién fue?
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:
    Roman Jakobson fue un lingüista ruso americano. Se considera una
    figura clave tanto en movimiento del /formalismo ruso/, así como
    en el /estructuralista/.  La lingüística de Jakobson se basa en
    los postulados de la lingüistica de Saussure, *pero* propuso una
    crítica a las ideas de Saussure.


*** Cita
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :BEAMER_ENV: block
    :END:
    #+begin_quote
    The fundamental role which these two operations play in language
    was clearly realized by Ferdinand de Saussure. Yet of the two
    varieties of combination-concurrence and concatenation-it was only
    the latter, the temporal sequence, which was recognized by the
    Geneva linguist. 
    \cite[99]{jakobson1956two}
    #+end_quote




** La pregunta
   

   
\begin{block}{}
   ¿Cómo medir
   computarizadamente la /literariedad/ de un texto según el marco de la
   lingüística de Jakobson?
\end{block}


* Objetivos
** General
   \begin{block}{General}

Diseñar e implementar un modelo que, dado un corpus de texto, produzca
   indicadores para el concepto de /literariedad/ que plantea Roman Jakobson.
     \end{block}
     
** Específicos
1) Construir el corpus necesario para representar el /eje sincrónico/.
2) Diseñar e implementar el algoritmo para calcular la /metáfora/ sobre un corpus.
3) Diseñar e implementar algoritmo para calcular la /metonimia/ sobre un corpus.
4) Seleccionar y unir los textos que serán procesados (corpus objetivo) por el algoritmo.
3) Correr el algoritmo sobre los corpus objetivo.
4) Evaluar el algoritmo de manera cuantitativa y cualitativa.

** Alcance

1) Modelos *naive*

2) Corpus de acceso libre (Brown Corpus)

3) Herramientas 'básicas' de NLP. (no Machine Learning)

* Marco teórico y referencial

** Introducción a metáfora y metonimia

*** Metáfora
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:

    \begin{figure}
    \includegraphics[width=\textwidth]{./assets/arte_dali.jpg}
   \caption{\emph{Cisnes reflejando elefantes} de Salvador Dalí}
    \end{figure}

*** Metonimia
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:

\begin{figure}
    \includegraphics[width=\textwidth]{./assets/arte_green.png}
\caption{\emph{9 grados} de Denise Green}
 \end{figure}

**  Metáfora y metonimia
*** Libro
   :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:
\begin{figure}
    \includegraphics[width=\textwidth]{./assets/cover_two_aspects.png}
\caption{\emph{9 grados} de Denise Green}
 \end{figure}

*** Citas
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:
    
   \tiny
   \begin{block}{Combinación/Metonimia}
Any linguistic sign involves two modes of arrangement:
Any sign is made up of constituent signs and/or
occurs only in combination with other signs. This means that any lin­
guistic unit at one and the same time serves as a context for simpler
units and/or finds its own context in a more complex linguistic unit.

   \end{block}

   \begin{block}{Selección/Metáfora}
A selection between alternatives implies the possibility
of substituting one for the other, equivalent in one respect and differ­
ent in another. Actually, selection and substitution are two faces of the
same operation.


   \end{block}

   \normal
* Diseño Metodológico
** Metodología
   \begin{figure}
    \includegraphics[width=\textwidth]{./assets/metodologia.png}

 \end{figure}

** Entendimiento del negocio
*** Entendimiento del negocio
    :PROPERTIES:
    :BEAMER_env: frame
    :END:
Cada algoritmo recibe un mensaje  $m$ de entrada con:
\begin{block}{Entrada}
\begin{itemize}
\item cadena de cualquier longitud
\item sin POS
\item sin set de entrenamiento
\end{itemize}
\end{block}
 produce:

\begin{block}{Salida}
\begin{itemize}
\item  Un valor continuo para dicho mensaje (no es categórico)
\item  Entre más alto el valor, más fuerte es esa característica (metáfora y/o metonímia)
\end{itemize}
\end{block}

*** Casos de uso
   :PROPERTIES:
   :BEAMER_env: frame
   :END:
    
   \begin{figure}
    \includegraphics[width=\textwidth]{./assets/posibles_usos.jpg}

 \end{figure}


*** Usuarios
    :PROPERTIES:
    :BEAMER_env: frame
    :END:
   
   \begin{figure}
 \includegraphics[width=0.24\textwidth]{./assets/negocio_metafora1.png}
 \includegraphics[width=0.24\textwidth]{./assets/negocio_metafora2.png}
 \includegraphics[width=0.24\textwidth]{./assets/negocio_metonimia1.png}
 \includegraphics[width=0.24\textwidth]{./assets/negocio_metonimia2.png}
   \end{figure}

** Entendimiento de los datos
*** Entendimiento de los datos :A: 
   :PROPERTIES:
    :BEAMER_env: frame
    :END:

**** texto
   :PROPERTIES:
   :BEAMER_COL: 0.48
   :END:
   
   Son esencialmente 3 componentes:

   \begin{block}{Corpus de referencia}
   Modela el estado actual de la /lengua/.
   Eje de sicnronía en Saussure.
   \end{block}

   \begin{block}{Red semántica}
    Modela el lenguaje: la capacidad de asociar ideas con símbolos.
   \end{block}

   \begin{block}{Corpus objetivo}
    Modela el /habla/.El mensaje que será sometido a análisis.
   \end{block}
  
   

**** graficos
    :PROPERTIES:
    :BEAMER_COL: 0.48
    :END:
    \begin{figure}
    \includegraphics[width=\textwidth]{./assets/sistema-comunicacion.png}
    \caption{Tomado de \cite{alonso1945curso}}
    \end{figure}

    \begin{figure}
 
    \includegraphics[width=\textwidth]{./assets/sistema-comunicacion2.png}
 \caption{Tomado de \cite{alonso1945curso}}
    \end{figure}

*** Resumen :B:
       :PROPERTIES:
    :BEAMER_env: frame
    :END:

 
    \begin{figure}
    \includegraphics[height=\textheight]{./assets/entendimiento_de_los_datos.png}

    \end{figure}

*** Corpus Brown :C:
          :PROPERTIES:
    :BEAMER_env: frame
    :END:

     Se seleccionó porque:
     \small
     \begin{itemize}
     \item todas las muestras del corpus pertenecen al año 1961,
     \item todas las muestras del corpus se imprimieron en Estados Unidos durante ese año,
     \item todos los autores son hablantes nativos de inglés,
     \item la categorización de las muestras fue hecha por un comité de expertos de la universidad de Brown,
     \item la intención declarada del corpus es la de ser una muestra representativa del inglés de aquel año,
     \item tiene una lista amplia de categorías que podrían ser útiles para observar diferencias entre las categorías,
     \item los resultados obtenidos del modelo podrían ser replicados porque el corpus es ampliamente conocido.
     \item el número de textos por categoría guarda la relación entre los textos publicados de esa categoría durante ese año y
     \item los resultados obtenidos del modelo podrían ser replicados porque el corpus es ampliamente conocido.
     \end{itemize}
     \normalsize

*** Wordnet :D:
          :PROPERTIES:
    :BEAMER_env: frame
    :END:


    \begin{block}{Definición}
    The main relation among words in WordNet is synonymy, as between the words shut and close or car and automobile.
    Synonyms--words that denote the same concept and are interchangeable in many contexts--are grouped into unordered sets (synsets).
    Each of WordNet’s 117 000 synsets is linked to other synsets by means of a small number of “conceptual relations.”
    \cite{fellbaum_1998}
    \end{block}
** Preparación de los datos
*** Preparación de los datos
    :PROPERTIES:
    :BEAMER_env: frame
    :END:
 \begin{figure}
 \includegraphics[width=\textwidth]{./assets/preparacion_visualizacion.png}
 \end{figure}

  \begin{block}{¿En qué consistió la preparación?}
  \begin{itemize}
  \item Conformar el corpus de referencia
  \item Conformar los corpus objetivo
  \item Controlar la mayor cantidad de variables
  \end{itemize}
  \end{block}
*** Resumen
    :PROPERTIES:
    :BEAMER_env: frame
    :END:
    
       \begin{table}[!ht]
      \centering

      \begin{tabular}{|c|c|}
      \hline
        Atributo & Cantidad \\ \hline
        Textos en corpus de referencia & 60 \\ \hline
        Categorías en corpus de referencia  & 13 \\ \hline
       Textos en corpus objetivo & 70 \\ \hline
       Textos en muestra de corpus objetivo & 14 \\ \hline
       Muestras de corpus objetivo & 5 \\ \hline
       Categorías por muestra & 14  \\ \hline
       Total de textos usados & 130  \\ \hline
      \end{tabular}
  \caption{Resumen de datos utilizados}
  \label{tab:resumen_preparacion}
  \end{table}

** Modelamiento
*** Modelamiento                                                          :A: 
   :PROPERTIES:
    :BEAMER_env: frame
    :END:
**** Metáfora   :texto:
    :PROPERTIES:
    :BEAMER_col: 0.48
    :END:

    \tiny
    \begin{block}{Metáfora}
\begin{equation}
\label{eq:mensaje}
mensaje = \{ w_1, w_2, w_3, \dots , w_j \}
\end{equation}

\begin{equation}
\label{eq:vector_semantico}
vector\ semantico(w) = \{s_1, s_2, s_3, \dots, s_j \} 
\end{equation}

\begin{equation}
\label{eq:vector_uso}
vector\ uso(w) = \{freq_{ref}(s_1),freq_{ref}(s_2),freq_{ref}(s_3), \dots, freq_{ref}(s_j) \} 
\end{equation}

\begin{equation}
\label{eq:promedio}
\mu = \frac{\Sigma_i^jfreq_{referencia}(s_i)}{j}
\end{equation}


\begin{equation}
\label{eq:uso}
uso(w) = \frac{freq_{objetivo}(w)}{\mu}
\end{equation}


\begin{equation}
\label{eq:indice_metafórico}
indice\ metaforico(mensaje) =  \Sigma_i^j uso(w_i)
\end{equation}
\end{block}
\normalsize
**** Ejemplo :ejemplo:
     :PROPERTIES:
     :BEAMER_col: 0.48
     :END:
     
         \begin{figure}
    \includegraphics[width=\textwidth]{./assets/codigo_vector_semantico.png}
    \caption{Ejemplo de implementación}
    \end{figure}

    \begin{figure}
 
    \includegraphics[width=\textwidth]{./assets/codigo_vector_uso.png}
 \caption{Ejemplo de implementación}
    \end{figure}

*** Modelamiento   :B:
       :PROPERTIES:
    :BEAMER_env: frame
    :END:

**** Texto :texto:
        :PROPERTIES:
    :BEAMER_col: 0.48
    :END:
\tiny
\begin{block}{Metonimia}
\begin{equation}
\label{eq:ngramas}
N = \{n_1, n_2, n_3, \dots , n_j\}
\end{equation}

\begin{equation}
\label{eq:metonimia}
met(n_i) = \frac{letras\ iguales}{ set(letras(n_i1) + letras(n_i2))}
\end{equation}

\begin{equation}\label{eq:indice_metonimia}
indice\ metonimia = \Sigma_i^j met(n_i)
\end{equation}
\end{block}
\normalsize
****  Ejemplo :ejemplo:
    :PROPERTIES:
    :BEAMER_col: 0.48
    :END:

    \begin{figure}
    \includegraphics[width=\textwidth]{./assets/codigo_metonimia.png}
    \caption{Ejemplo de implementación}
    \end{figure}

    \begin{figure}
 
    \includegraphics[width=\textwidth]{./assets/metonimia.jpg}
    \caption{Concepto de metonimia}
    \end{figure}

    
*** Diseño experimental                                                   :C:
    :PROPERTIES:
    :BEAMER_env: frame
    :END:
**** Criterios cualitativos
   - H_1: Se espera que las categorías de ficción tengan un índice metafórico significativamente mayor que los de no-ficción.
   - H_2: Se espera que las categorias 'Reportage' y 'Editorial' tengan índices metafóricos similares a través de las muestras.
   - H_3: Se espera que la categoría 'Belles Lettres' tenga un indíce metafórico más alta entre las categorías de no-ficción.
   - H_4: Se espera que la categoria 'Learned' tenga un indice metonímico bajo en general.
**** Criterios cuantitativos
     Prueba ANOVA: ¿Los resultados que se obtuvieron son aleatorios?
** Despliegue
*** Resultados por categorías
  :PROPERTIES:
  :BEAMER_env: frame
  :END:

**** Metafora
     :PROPERTIES:
     :BEAMER_col: 0.48
     :END:
\begin{figure}[H]
\centering
\includegraphics[width=\linewidth]{./resultados/graphs/total/accum_cat_metafora.png}

\caption{Metáfora través de las muestras }
\end{figure}

**** Metonimia
     :PROPERTIES:
     :BEAMER_col: 0.48
     :END:
     
\begin{figure}[H]
\includegraphics[width=\linewidth]{./resultados/graphs/total/accum_cat_metonimia.png}
\caption{Metonimia través de las muestras }
\centering

\end{figure}

*** Resultados por metacategorías
 :PROPERTIES:
  :BEAMER_env: frame
  :END:
**** Metafora
     :PROPERTIES:
     :BEAMER_col: 0.48
     :END:
     
\begin{figure}[H]
\centering
\includegraphics[width=0.9\linewidth]{./resultados/graphs/total/metafora_total.png}
\caption{\label{fig:metafora_total} Índice metafórico por metacategorías a través de muestras }
\end{figure}


**** Metonimia
     :PROPERTIES:
     :BEAMER_col: 0.48
     :END:
     
\begin{figure}[H]
\centering
\includegraphics[width=0.9\linewidth]{./resultados/graphs/total/metonimia_total.png}
\caption{\label{fig:metonimia_total} Índice metonímico por metacategoria a través de muestras }
\end{figure}

** Evaluación
       :PROPERTIES:
    :BEAMER_env: frame
    :END:
**** Criterios cualitativos
     :PROPERTIES:
    :BEAMER_col: 0.48
    :END:
  \begin{block}{Criterios cualitativos}
  \begin{table}[H]
  

      \begin{tabular}{|l|l|l}
      \hline
	 Criterio     &  Evaluación \\ \hline
         H_{1}  & Cumplió  \\
         H_{2}  & Cumplió\\
        H_{3}  & No cumplió \\
        H_{4}  & Cumplió\\
\hline
      \end{tabular}

  \end{table}
  \end{block}

**** Criterios cuantitativos
     :PROPERTIES:
    :BEAMER_col: 0.48
    :END:
 \begin{block}{Criterios cuantitativos}
  \begin{table}[H]
   

      \begin{tabular}{|l|l|l|}
      \hline
	 Indicador     &  F & p-value \\ \hline
         Metafora  & 51.41 & 9.81^{-10}  \\
         Metonimia  & 4.32 & 0.04 \\
         \hline

      \end{tabular}

  \end{table}
 \end{block}

** Conclusiones

   1) Los algoritmos propuestos producen un valor cuantitativo que es
   capaz de 'distinguir' entre dos metacategorias: los textos de
   ficción y los de no ficción, puntuándolos más alto o más bajo
   según corresponda.

2) Un enfoque basado en frequencias como el de /bag of words/ parece
   ser suficiente para modelar los conceptos de /metafora/ y
   /metonimia/.  Los resultados parecen avalar las observaciones de de
   Jakobson en torno a la relación de la metonimia con textos más
   afines al polo 'Realista' (periódicos, reportes, artículos, etc) y
   la metáfora con textos afines al polo del 'Romanticismo'
   (historias, fábulas, fantasía, etc).

3) Este enfoque tiene algunas ventajas y desventajas con respecto a un
   enfoque de Machine Learning. Como ventaja, no se requiere un
   /training set/. Como desventaja, el valor de los índices debe ser
   comparado entre textos según un contexto dado por el corpus de
   referencia. Esta, sin embargo, es la postura estructuralista, pues
   una apreciación literaria siempre se hace con respecto a otra.
   

\bibliographystyle{ieeetr}
\bibliography{biblio} 
   
